name = "missiai"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]

[[kv_namespaces]]
binding = "MISSI_MEMORY"
id = "ddf2e5eb21484fd1a9aecd8e4eaada74"